job:
  tags:
    - appium 

  script: 
    - git config core.longpaths true
    - |
      cd C:\gitlab-runner\builds\gkfSkrp7\0\spirit-digital\SpiritDigital.CliniTouchVie.Application.Testing\CTV.Application.SpecFlowAppiumTests
    - dotnet build CTV.Application.SpecFlowAppiumTests.csproj