variables:
    GIT_CLONE_PATH: "$CI_BUILDS_DIR\\$CI_PROJECT_NAME"
    FF_ENABLE_JOB_CLEANUP: 1

test:
  tags:
    - appium
  script: 
    - cd $GIT_CLONE_PATH
    - powershell -Command Set-Executionpolicy -ExecutionPolicy Unrestricted -Scope Process
    - echo "Authenticate with Xray"
    - 'token= curl.exe -H "Content-Type: application/json" -X POST https://xray.cloud.getxray.app/api/v2/authenticate'