variables:
  GIT_CLONE_PATH: /CTVAndroid/

before_script:


job:
  tags:
    - appium 

  script: 
    - |
      cd C:\gitlab-runner\builds\gkfSkrp7\0\spirit-digital\SpiritDigital.CliniTouchVie.Application.Testing\CTV.Application.SpecFlowAppiumTests
    - dotnet build CTV.Application.SpecFlowAppiumTests.csproj