variables:
    GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME'
    FF_ENABLE_JOB_CLEANUP: 1

stages: 
  - test


test:
  tags:
    - appium
  script: 
    - |
      cd $GIT_CLONE_PATH
    - powershell -Command Set-Executionpolicy -ExecutionPolicy Unrestricted -Scope Process
    - echo "Authenticate with Xray"
    - |
        export token=$(curl -H "Content-Type: application/json" -X POST --data "{\"client_id\": \"$client_id\", \"client_secret\": \"$client_secret\" }" https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"')
    - echo "Fetching feature file ${TEST_CASE_ID} from JIRA"
    - | 
      curl -H "Content-Type: application/json" -X GET -H "Authorization: Bearer ${token}" "https://xray.cloud.getxray.app/api/v2/export/cucumber?filter=10124" -o features.zip
      unzip -o features.zip -d CTV.Application.SpecFlowAppiumTests\Features\
    - dotnet test CTV.Application.SpecFlowAppiumTests\CTV.Application.SpecFlowAppiumTests.csproj --results-directory "$GIT_CLONE_PATH"
    - mv data.json "C:\Temp\"
    - echo "Uploading results to JIRA"
    - |
      curl -H "Content-Type: application/json" -H "Authorization: Bearer ${token}"  --data-binary "C:\Temp\data.json" -i -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/cucumber"

