variables:
    GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME'
    FF_ENABLE_JOB_CLEANUP: 1

stages: 
  - test


test:
  tags:
    - appium
  script: 
    - |
      cd $GIT_CLONE_PATH
    - powershell -Command Set-Executionpolicy -ExecutionPolicy Unrestricted -Scope Process
    - echo "Authenticate with Xray"
    - |
      $token= curl.exe -H "Content-Type: application/json" -X POST --data '{"client_id":"ADE543CB4F3642259C5E5AA30FD472E7","client_secret": "18e85b583cf919eddcd28c45e9bf1e71463158c6c01d39316a7da73046559ec7"}' https://xray.cloud.getxray.app/api/v2/authenticate
    - echo $token 
    - echo "Fetching feature files from JIRA"
    - |
      curl.exe -H "Content-Type: application/json" -H "Authorization: Bearer ${token}" -o features.zip -X GET  https://xray.cloud.getxray.app/api/v2/export/cucumber?filter=10124 
    -  Expand-Archive features.zip -DestinationPath $GIT_CLONE_PATH\CTV.Application.SpecFlowAppiumTests\Features\ -Force -PassThru
    - dotnet test CTV.Application.SpecFlowAppiumTests\CTV.Application.SpecFlowAppiumTests.csproj --results-directory "$GIT_CLONE_PATH"
    - mv data.json "C:\Temp\"
    - echo "Uploading results to JIRA"
    - |
      curl.exe -H "Content-Type: application/json" -H "Authorization: Bearer ${token}"  --data-binary "C:\Temp\data.json" -i -X POST "https://xray.cloud.getxray.app/api/v2/import/execution/cucumber"

