before_script:
  - git config core.longpaths true

job:
  tags:
    - appium 

  script: 
    - |
      cd C:\gitlab-runner\builds\gkfSkrp7\0\spirit-digital\SpiritDigital.CliniTouchVie.Application.Testing\CTV.Application.SpecFlowAppiumTests
    - dotnet build CTV.Application.SpecFlowAppiumTests.csproj