variables:
  GIT_CLONE_PATH: /CTVAndroid/

before_script:
  - |
    cd C:/gitlab-runner/${GIT_CLONE_PATH}

job:
  tags:
    - appium 

  script: dotnet build CTV.Application.SpecFlowAppiumTests.csproj