variables:
    GIT_CLONE_PATH: "$CI_BUILDS_DIR\\$CI_PROJECT_NAME"
    #FF_ENABLE_JOB_CLEANUP: 1

stages:
 - deploy 
 - android-test

fetch-apk:
  stage: deploy
  tags: 
    - appium
  script:
    - powershell -Command Set-Executionpolicy -ExecutionPolicy Unrestricted -Scope Process
    - cd $GIT_CLONE_PATH
    - 'curl.exe --location --header "PRIVATE-TOKEN: glpat-g1yfRMQTDTShu1DPUyz2" -X GET https://gitlab.com/api/v4//projects/27135546/jobs/artifacts/master/download?job=assembleRelease -o artifacts.zip'
    - Expand-Archive -Path artifacts.zip -DestinationPath $GIT_CLONE_PATH\testAPK\ -Force
    - mv "$GIT_CLONE_PATH\testAPK\CliniTouchVie\app\build\outputs\apk\release\app-release-unsigned.apk" "C:\TestAPK\CTV\" -Force


android-test:
  stage: android-test
  tags:
    - appium
  script: 
    - cd $GIT_CLONE_PATH
    - powershell -Command Set-Executionpolicy -ExecutionPolicy Unrestricted -Scope Process
    - $env:PLATFORM = "Android"
    - echo "Authenticate with Xray"
    - '$token= curl.exe -H "Content-Type: application/json" -X POST --data "{ \`"client_id\`": \`"ADE543CB4F3642259C5E5AA30FD472E7\`",\`"client_secret\`": \`"$XRAY_CLIENT_SECRET\`" }" https://xray.cloud.getxray.app/api/v2/authenticate'
    - echo "Fetching feature files from JIRA"
    - 'curl.exe -H "Content-Type: application/json" -H "Authorization: Bearer ${token}" -X GET https://xray.cloud.getxray.app/api/v2/export/cucumber?filter=10124 -o features.zip'
    - Expand-Archive -Path features.zip -DestinationPath $GIT_CLONE_PATH\CTV.Application.SpecFlowAppiumTests\Features -Force
    - dotnet test CTV.Application.SpecFlowAppiumTests\SpecFlowAppiumTests.csproj --results-directory "$GIT_CLONE_PATH"
    - mv data.json "C:\Temp\Android\" -Force
    - echo "Uploading results to JIRA"
    - 'curl.exe -H "Content-Type: application/json" -H "Authorization: Bearer ${token}" --data-binary "@C:\Temp\Android\data.json" -X POST https://xray.cloud.getxray.app/api/v2/import/execution/cucumber'
    - echo "Android task complete"
  allow_failure: true