job:
  tags:
    - appium 

  script: 
    - |
      cd $CI_BUILDS_DIR
    - powershell -Command Set-Executionpolicy -ExecutionPolicy Unrestricted -Scope Process
    - echo $CI_BUILDS_DIR
    - echo $PWD