// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CTV.Application.SpecFlowAppiumTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Activation elements are visible", SourceFile="Features\\1_SKP-42.feature", SourceLine=0)]
    public partial class ActivationElementsAreVisibleFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "1_SKP-42.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Activation elements are visible", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ActivationElementsAreVisible(string title, string view, string element, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "TEST_SCAA-97"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("title", title);
            argumentsOfScenario.Add("view", view);
            argumentsOfScenario.Add("element", element);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Activation elements are visible", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 9
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 10
  testRunner.Given("the app is running", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
  testRunner.When(string.Format("the user is on the {0} screen", view), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
  testRunner.Then(string.Format("they are able to see the expected element {0}", element), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Activation elements are visible, CompanyLogo", new string[] {
                "TEST_SCAA-97"}, SourceLine=15)]
        public virtual void ActivationElementsAreVisible_CompanyLogo()
        {
#line 9
 this.ActivationElementsAreVisible("CompanyLogo", "Activation", "companyLogoImage", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Activation elements are visible, ActivationTitle", new string[] {
                "TEST_SCAA-97"}, SourceLine=15)]
        public virtual void ActivationElementsAreVisible_ActivationTitle()
        {
#line 9
 this.ActivationElementsAreVisible("ActivationTitle", "Activation", "activationTitle", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Activation elements are visible, ActivationDesc", new string[] {
                "TEST_SCAA-97"}, SourceLine=15)]
        public virtual void ActivationElementsAreVisible_ActivationDesc()
        {
#line 9
 this.ActivationElementsAreVisible("ActivationDesc", "Activation", "activationDesc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Activation elements are visible, CodeField", new string[] {
                "TEST_SCAA-97"}, SourceLine=15)]
        public virtual void ActivationElementsAreVisible_CodeField()
        {
#line 9
 this.ActivationElementsAreVisible("CodeField", "Activation", "activationCodeInput", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Activation elements are visible, ActivationButton", new string[] {
                "TEST_SCAA-97"}, SourceLine=15)]
        public virtual void ActivationElementsAreVisible_ActivationButton()
        {
#line 9
 this.ActivationElementsAreVisible("ActivationButton", "Activation", "activationContinueInput", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Activation elements are visible, T and C\'s", new string[] {
                "TEST_SCAA-97"}, SourceLine=15)]
        public virtual void ActivationElementsAreVisible_TAndCs()
        {
#line 9
 this.ActivationElementsAreVisible("T and C\'s", "Activation", "termsAgreedInput", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
